### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by efr3m** [brettc/partitionfinder#28] opened 2015-01-23 11:53 UTC
I am following the isntruction for installing the phyml on Biolinux that uses Ubuntu 14.04.
However, when I type

    make
    make  all-recursive
    make[1]: Entering directory `/usr/local/lib/partitionfinder-master/programs/phyml_source'
    Making all in src
    make[2]: Entering directory `/usr/local/lib/partitionfinder-master/programs/phyml_source/src'

    :: Building [phytime]. Version 20150123 ::

    gcc  -I. -I..     -ansi -pedantic -Wall -std=c99 -O3 -fomit-frame-pointer -funroll-loops -arch i386      -mmacosx-version-min=10.4 -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.c
    gcc: error: i386: No such file or directory
    gcc: error: unrecognized command line option ‘-arch’
    gcc: error: unrecognized command line option ‘-mmacosx-version-min=10.4’
    make[2]: *** [main.o] Error 1
    make[2]: Leaving directory `/usr/local/lib/partitionfinder-master/programs/phyml_source/src'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/usr/local/lib/partitionfinder-master/programs/phyml_source'
    make: *** [all] Error 2

Any idea what is the reasonn for these errors?
thanks

**Comment by roblanf** [comment] 2015-01-23 22:00
Hi,

Unfortunately I have no idea what the issue is here: we didn't write PhyML, and we can't offer support. Perhaps it's worth trying the latest version of PhyML instead, though I can't be sure that this will work with PF. 

Sorry - I know this is frustrating. However, we are working on PF2, and should have issues such as this resolved in the next couple of months. 

Rob

**Closed by roblanf** 2015-01-23 22:00 UTC
